language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script: npm test
notifications:
  slack:
    rooms:
      secure: qlcOCL9IhKy/501hPiETSAkGRsjfhHbsQPfjRNSWZaPYvvzIA07/3QgcqsV6gIThLIuplGdlOK+IOjZkW8k0V7tlljcEPaabN5q2E84pXicmxK1fqz9I4lpHcXaIzs0JXQWHNcoubxZezVeD4oRxFg+sjp0XbiET8MSpCtmTEXyjnCMjN1vC0gbZp0qSxWzZgAAjtgpcPSbn7ctrmWgCkTg7gCz1xmGZ9Bt75RdEjouEZCkU/V2RQ+AG7EQS3u14lqVt3Oj+uYCHQ6z4LfffyrHmsM7v2X7+tJmvBwCWMvX8HbAsa52aWnz2ZxtX4LxW5BZww45f+v3kdaJLzAEldHGHDct8MSX+EW5AkWYBXj6APIJ43IC8+twZm8IqaMiaDjFn2JSKf90JqamcoAPA9sFYQ+Rdfeb9fEyWTDgn9PVHMxVZV5T+4H2PZRBnrtOWYrrrf5P4/NMNZj5wj9jdFncnXvDjCzJoLaRVhpW2vzFWkCM/OLepHCR3OjaJmnUjNeGVlempgzBiwsTA/br9ZHCQu8lYXfYmmY76hbXNBPjyriiBrFcso81RWamwBFR+7p3V5Wf1tqzd7H/gWdZoGgfklQqtWrDIUzQb41oSgKEeiynraoxyhy96SzaJEn1AWT16bqv9ec+Ef+PtFA5YSFx2gVw+1QANOP3Y5qKpdrU=
